# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_template.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(773, 360)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_name = QtGui.QLineEdit(Dialog)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.lineEdit_model = QtGui.QLineEdit(Dialog)
        self.lineEdit_model.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_model.setObjectName(_fromUtf8("lineEdit_model"))
        self.gridLayout.addWidget(self.lineEdit_model, 0, 3, 1, 1)
        self.lineEdit_manufacture = QtGui.QLineEdit(Dialog)
        self.lineEdit_manufacture.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_manufacture.setObjectName(_fromUtf8("lineEdit_manufacture"))
        self.gridLayout.addWidget(self.lineEdit_manufacture, 0, 5, 1, 1)
        self.doubleSpinBox_requisition_sum = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_requisition_sum.setEnabled(False)
        self.doubleSpinBox_requisition_sum.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_requisition_sum.setReadOnly(True)
        self.doubleSpinBox_requisition_sum.setMaximum(999999999.99)
        self.doubleSpinBox_requisition_sum.setProperty("value", 1234.56)
        self.doubleSpinBox_requisition_sum.setObjectName(_fromUtf8("doubleSpinBox_requisition_sum"))
        self.gridLayout.addWidget(self.doubleSpinBox_requisition_sum, 2, 3, 1, 1)
        self.doubleSpinBox_acceptance_price = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_acceptance_price.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_acceptance_price.setMaximum(999999999.99)
        self.doubleSpinBox_acceptance_price.setProperty("value", 1234.56)
        self.doubleSpinBox_acceptance_price.setObjectName(_fromUtf8("doubleSpinBox_acceptance_price"))
        self.gridLayout.addWidget(self.doubleSpinBox_acceptance_price, 2, 5, 1, 1)
        self.doubleSpinBox_quotation_price = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_quotation_price.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_quotation_price.setMaximum(999999999.99)
        self.doubleSpinBox_quotation_price.setProperty("value", 1234.56)
        self.doubleSpinBox_quotation_price.setObjectName(_fromUtf8("doubleSpinBox_quotation_price"))
        self.gridLayout.addWidget(self.doubleSpinBox_quotation_price, 1, 5, 1, 1)
        self.comboBox_quotation_currency = QtGui.QComboBox(Dialog)
        self.comboBox_quotation_currency.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_quotation_currency.setObjectName(_fromUtf8("comboBox_quotation_currency"))
        self.comboBox_quotation_currency.addItem(_fromUtf8(""))
        self.comboBox_quotation_currency.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_quotation_currency, 1, 7, 1, 1)
        self.doubleSpinBox_acceptance_sum = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_acceptance_sum.setEnabled(False)
        self.doubleSpinBox_acceptance_sum.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_acceptance_sum.setReadOnly(True)
        self.doubleSpinBox_acceptance_sum.setMaximum(999999999.99)
        self.doubleSpinBox_acceptance_sum.setProperty("value", 1234.56)
        self.doubleSpinBox_acceptance_sum.setObjectName(_fromUtf8("doubleSpinBox_acceptance_sum"))
        self.gridLayout.addWidget(self.doubleSpinBox_acceptance_sum, 2, 7, 1, 1)
        self.doubleSpinBox_requisition_price = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_requisition_price.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_requisition_price.setMaximum(999999999.99)
        self.doubleSpinBox_requisition_price.setProperty("value", 1234.56)
        self.doubleSpinBox_requisition_price.setObjectName(_fromUtf8("doubleSpinBox_requisition_price"))
        self.gridLayout.addWidget(self.doubleSpinBox_requisition_price, 2, 1, 1, 1)
        self.comboBox_property_type = QtGui.QComboBox(Dialog)
        self.comboBox_property_type.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_property_type.setObjectName(_fromUtf8("comboBox_property_type"))
        self.comboBox_property_type.addItem(_fromUtf8(""))
        self.comboBox_property_type.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_property_type, 0, 7, 1, 1)
        self.doubleSpinBox_quantity = QtGui.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_quantity.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_quantity.setMaximum(999999999.99)
        self.doubleSpinBox_quantity.setProperty("value", 1234.56)
        self.doubleSpinBox_quantity.setObjectName(_fromUtf8("doubleSpinBox_quantity"))
        self.gridLayout.addWidget(self.doubleSpinBox_quantity, 1, 3, 1, 1)
        self.lineEdit_unit = QtGui.QLineEdit(Dialog)
        self.lineEdit_unit.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEdit_unit.setObjectName(_fromUtf8("lineEdit_unit"))
        self.gridLayout.addWidget(self.lineEdit_unit, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 6, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 4, 1, 1)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 2, 6, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtGui.QPlainTextEdit(Dialog)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtGui.QPushButton(Dialog)
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtGui.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.pushButton_ok, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Dialog.accept)
        QtCore.QObject.connect(self.pushButton_cancel, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.lineEdit_name.setText(_translate("Dialog", "针式打印机", None))
        self.lineEdit_model.setText(_translate("Dialog", "LQ-80KF", None))
        self.lineEdit_manufacture.setText(_translate("Dialog", "爱普生中国有限公司", None))
        self.comboBox_quotation_currency.setItemText(0, _translate("Dialog", "美元", None))
        self.comboBox_quotation_currency.setItemText(1, _translate("Dialog", "英镑", None))
        self.comboBox_property_type.setItemText(0, _translate("Dialog", "固定资产", None))
        self.comboBox_property_type.setItemText(1, _translate("Dialog", "材料消耗品", None))
        self.lineEdit_unit.setText(_translate("Dialog", "台", None))
        self.label_2.setText(_translate("Dialog", "产品名称", None))
        self.label_3.setText(_translate("Dialog", "型号规格", None))
        self.label_4.setText(_translate("Dialog", "生产厂家", None))
        self.label_5.setText(_translate("Dialog", "资产类型", None))
        self.label_6.setText(_translate("Dialog", "单位", None))
        self.label_7.setText(_translate("Dialog", "数量", None))
        self.label_8.setText(_translate("Dialog", "原始报价", None))
        self.label_9.setText(_translate("Dialog", "报价币种", None))
        self.label_10.setText(_translate("Dialog", "请购价格", None))
        self.label_11.setText(_translate("Dialog", "请购金额", None))
        self.label_12.setText(_translate("Dialog", "结算价格", None))
        self.label_13.setText(_translate("Dialog", "结算金额", None))
        self.label.setText(_translate("Dialog", "设备参数描述（固定资产卡片）", None))
        self.pushButton_ok.setText(_translate("Dialog", "确认", None))
        self.pushButton_cancel.setText(_translate("Dialog", "取消", None))
