# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requisition_template.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(514, 236)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.comboBox_applicant = QtGui.QComboBox(self.groupBox)
        self.comboBox_applicant.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_applicant.setObjectName(_fromUtf8("comboBox_applicant"))
        self.gridLayout.addWidget(self.comboBox_applicant, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_project = QtGui.QComboBox(self.groupBox)
        self.comboBox_project.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_project.setObjectName(_fromUtf8("comboBox_project"))
        self.gridLayout.addWidget(self.comboBox_project, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_project_info = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_project_info.setText(_fromUtf8(""))
        self.lineEdit_project_info.setReadOnly(True)
        self.lineEdit_project_info.setObjectName(_fromUtf8("lineEdit_project_info"))
        self.gridLayout.addWidget(self.lineEdit_project_info, 2, 3, 1, 3)
        self.lineEdit_request_title = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_request_title.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEdit_request_title.setObjectName(_fromUtf8("lineEdit_request_title"))
        self.gridLayout.addWidget(self.lineEdit_request_title, 0, 1, 1, 5)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 2, 1, 1)
        self.dateEdit_request_date = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_request_date.sizePolicy().hasHeightForWidth())
        self.dateEdit_request_date.setSizePolicy(sizePolicy)
        self.dateEdit_request_date.setMinimumSize(QtCore.QSize(100, 0))
        self.dateEdit_request_date.setObjectName(_fromUtf8("dateEdit_request_date"))
        self.gridLayout.addWidget(self.dateEdit_request_date, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.comboBox_purchase_type = QtGui.QComboBox(self.groupBox)
        self.comboBox_purchase_type.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_purchase_type.setObjectName(_fromUtf8("comboBox_purchase_type"))
        self.gridLayout.addWidget(self.comboBox_purchase_type, 1, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.comboBox_purchase_method = QtGui.QComboBox(self.groupBox)
        self.comboBox_purchase_method.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_purchase_method.setObjectName(_fromUtf8("comboBox_purchase_method"))
        self.gridLayout_3.addWidget(self.comboBox_purchase_method, 0, 1, 1, 1)
        self.doubleSpinBox_budget = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_budget.setEnabled(False)
        self.doubleSpinBox_budget.setMinimumSize(QtCore.QSize(100, 0))
        self.doubleSpinBox_budget.setObjectName(_fromUtf8("doubleSpinBox_budget"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_budget, 0, 5, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 0, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 0, 4, 1, 1)
        self.frame = QtGui.QFrame(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_yes = QtGui.QRadioButton(self.frame)
        self.radioButton_yes.setObjectName(_fromUtf8("radioButton_yes"))
        self.horizontalLayout.addWidget(self.radioButton_yes)
        self.radioButton_no = QtGui.QRadioButton(self.frame)
        self.radioButton_no.setChecked(True)
        self.radioButton_no.setObjectName(_fromUtf8("radioButton_no"))
        self.horizontalLayout.addWidget(self.radioButton_no)
        self.gridLayout_3.addWidget(self.frame, 0, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox)
        self.label_16.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.lineEdit_purchase_reason = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_purchase_reason.setObjectName(_fromUtf8("lineEdit_purchase_reason"))
        self.gridLayout_4.addWidget(self.lineEdit_purchase_reason, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.toolButton_reason_gen = QtGui.QToolButton(self.groupBox)
        self.toolButton_reason_gen.setObjectName(_fromUtf8("toolButton_reason_gen"))
        self.gridLayout_4.addWidget(self.toolButton_reason_gen, 0, 2, 1, 1)
        self.lineEdit_tech_spec = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_tech_spec.setObjectName(_fromUtf8("lineEdit_tech_spec"))
        self.gridLayout_4.addWidget(self.lineEdit_tech_spec, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.radioButton_yes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")),
                               self.doubleSpinBox_budget.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.groupBox.setTitle(_translate("Form", "请购信息", None))
        self.label_6.setText(_translate("Form", "课题信息", None))
        self.label_2.setText(_translate("Form", "课题编号", None))
        self.label_3.setText(_translate("Form", "申请人", None))
        self.label_4.setText(_translate("Form", "申请项目", None))
        self.lineEdit_request_title.setText(_translate("Form", "大功率飞秒激光器系统", None))
        self.label.setText(_translate("Form", "申请日期", None))
        self.dateEdit_request_date.setDisplayFormat(_translate("Form", "yyyy-M-d", None))
        self.label_7.setText(_translate("Form", "采购分类", None))
        self.label_14.setText(_translate("Form", "是否预算", None))
        self.label_15.setText(_translate("Form", "预算金额", None))
        self.radioButton_yes.setText(_translate("Form", "是", None))
        self.radioButton_no.setText(_translate("Form", "否", None))
        self.label_16.setText(_translate("Form", "采购方式", None))
        self.label_18.setText(_translate("Form", "采购理由", None))
        self.label_19.setText(_translate("Form", "技术指标", None))
        self.toolButton_reason_gen.setText(_translate("Form", "...", None))
