# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requisition_template.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1082, 106)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_request_reason = QtGui.QLineEdit(Form)
        self.lineEdit_request_reason.setMaxLength(80)
        self.lineEdit_request_reason.setObjectName(_fromUtf8("lineEdit_request_reason"))
        self.gridLayout.addWidget(self.lineEdit_request_reason, 2, 1, 1, 10)
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 1)
        self.comboBox_purchase_category = QtGui.QComboBox(Form)
        self.comboBox_purchase_category.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_purchase_category.setMaximumSize(QtCore.QSize(120, 100))
        self.comboBox_purchase_category.setObjectName(_fromUtf8("comboBox_purchase_category"))
        self.gridLayout.addWidget(self.comboBox_purchase_category, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_purchase_method = QtGui.QComboBox(Form)
        self.comboBox_purchase_method.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_purchase_method.setMaximumSize(QtCore.QSize(120, 100))
        self.comboBox_purchase_method.setObjectName(_fromUtf8("comboBox_purchase_method"))
        self.gridLayout.addWidget(self.comboBox_purchase_method, 0, 7, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 10, 1, 1)
        self.comboBox_applicant = QtGui.QComboBox(Form)
        self.comboBox_applicant.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_applicant.setMaximumSize(QtCore.QSize(120, 100))
        self.comboBox_applicant.setObjectName(_fromUtf8("comboBox_applicant"))
        self.gridLayout.addWidget(self.comboBox_applicant, 0, 9, 1, 1)
        self.comboBox_project = QtGui.QComboBox(Form)
        self.comboBox_project.setMinimumSize(QtCore.QSize(120, 0))
        self.comboBox_project.setMaximumSize(QtCore.QSize(120, 100))
        self.comboBox_project.setObjectName(_fromUtf8("comboBox_project"))
        self.gridLayout.addWidget(self.comboBox_project, 1, 5, 1, 1)
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 6, 1, 1)
        self.doubleSpinBox_budget_amount = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBox_budget_amount.setEnabled(False)
        self.doubleSpinBox_budget_amount.setMinimumSize(QtCore.QSize(120, 0))
        self.doubleSpinBox_budget_amount.setMaximumSize(QtCore.QSize(120, 100))
        self.doubleSpinBox_budget_amount.setMaximum(999999999.99)
        self.doubleSpinBox_budget_amount.setObjectName(_fromUtf8("doubleSpinBox_budget_amount"))
        self.gridLayout.addWidget(self.doubleSpinBox_budget_amount, 1, 3, 1, 1)
        self.dateEdit_request_date = QtGui.QDateEdit(Form)
        self.dateEdit_request_date.setMinimumSize(QtCore.QSize(120, 0))
        self.dateEdit_request_date.setMaximumSize(QtCore.QSize(120, 100))
        self.dateEdit_request_date.setObjectName(_fromUtf8("dateEdit_request_date"))
        self.gridLayout.addWidget(self.dateEdit_request_date, 0, 11, 1, 1)
        self.lineEdit_request_title = QtGui.QLineEdit(Form)
        self.lineEdit_request_title.setText(_fromUtf8(""))
        self.lineEdit_request_title.setObjectName(_fromUtf8("lineEdit_request_title"))
        self.gridLayout.addWidget(self.lineEdit_request_title, 0, 1, 1, 3)
        self.lineEdit_project_info = QtGui.QLineEdit(Form)
        self.lineEdit_project_info.setEnabled(False)
        self.lineEdit_project_info.setReadOnly(True)
        self.lineEdit_project_info.setObjectName(_fromUtf8("lineEdit_project_info"))
        self.gridLayout.addWidget(self.lineEdit_project_info, 1, 7, 1, 5)
        self.label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(120, 0))
        self.frame.setMaximumSize(QtCore.QSize(120, 100))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_yes = QtGui.QRadioButton(self.frame)
        self.radioButton_yes.setObjectName(_fromUtf8("radioButton_yes"))
        self.horizontalLayout.addWidget(self.radioButton_yes)
        self.radioButton_no = QtGui.QRadioButton(self.frame)
        self.radioButton_no.setChecked(True)
        self.radioButton_no.setObjectName(_fromUtf8("radioButton_no"))
        self.horizontalLayout.addWidget(self.radioButton_no)
        self.gridLayout.addWidget(self.frame, 1, 1, 1, 1)
        self.pushButton_preset_reasons = QtGui.QPushButton(Form)
        self.pushButton_preset_reasons.setObjectName(_fromUtf8("pushButton_preset_reasons"))
        self.gridLayout.addWidget(self.pushButton_preset_reasons, 2, 11, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.radioButton_yes, QtCore.SIGNAL(_fromUtf8("toggled(bool)")),
                               self.doubleSpinBox_budget_amount.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.lineEdit_request_reason.setPlaceholderText(_translate("Form", "对于金额在五万以上的请购需要填写", None))
        self.label_10.setText(_translate("Form", "申请理由", None))
        self.label_7.setText(_translate("Form", "预算金额", None))
        self.label_3.setText(_translate("Form", "申请人", None))
        self.label_2.setText(_translate("Form", "采购分类", None))
        self.label_8.setText(_translate("Form", "课题编号", None))
        self.label_5.setText(_translate("Form", "采购方式", None))
        self.label_6.setText(_translate("Form", "是否预算", None))
        self.label_4.setText(_translate("Form", "申请日期", None))
        self.label_9.setText(_translate("Form", "课题信息", None))
        self.dateEdit_request_date.setDisplayFormat(_translate("Form", "yyyy-M-d", None))
        self.lineEdit_request_title.setPlaceholderText(_translate("Form", "必填", None))
        self.label.setText(_translate("Form", "申请标题", None))
        self.radioButton_yes.setText(_translate("Form", "是", None))
        self.radioButton_no.setText(_translate("Form", "否", None))
        self.pushButton_preset_reasons.setText(_translate("Form", "预设信息", None))
